apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-jmeter-deployment
  namespace: wso2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-jmeter
  template:
    metadata:
      labels:
        app: client-jmeter
    spec:
      containers:
        - name: client-jmeter
          image: ubuntu:latest
          resources:
            requests:
              memory: "4Gi"
              cpu: "4"
            limits:
              memory: "4Gi"
              cpu: "4"
          command: ["/bin/bash", "-c"]
          args: ["apt update && echo 'start to install java-8' && apt install -y openjdk-8-jdk && echo 'Start to run Jmeter Scripts' && /home/apache-jmeter-4.0/bin/jmeter -n -t /home/jmeter-scripts/HTTPSPostRequest.jmx -l /home/jmeter-results/HTTPSPostRequest-results-$HOSTNAME.jtl"]
          volumeMounts:
            - name: clent-artifats-storage-volume
              mountPath: "/home"
      volumes:
        - name: clent-artifats-storage-volume
          persistentVolumeClaim:
            claimName: clent-artifats-storage-volume-claim