# Copyright (c) 2017, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wso2apim-store-publisher
  namespace: wso2
  labels:
    app: wso2apim-store-publisher
    node: store-local
    pattern: wso2apim-pattern-3
spec:
  selector:
    matchLabels:
      app: wso2apim-store-publisher
      node: store-publisher-local
      pattern: wso2apim-pattern-3
  template:
    metadata:
      labels:
        app: wso2apim-store-publisher
        node: store-publisher-local
        pattern: wso2apim-pattern-3
    spec:
      containers:
        - image: virajhasith/wso2am-2.5.0:1621359805584withLogPatches
          #        image: virajhasith/wso2am-2.5.0:1621359805584withPatches
          #        image: virajhasith/wso2am-2.5.0:1621359805584
          name: wso2apim
          imagePullPolicy: IfNotPresent
          ports:
            -
              containerPort: 9763
              protocol: "TCP"
            -
              containerPort: 9443
              protocol: "TCP"
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 150
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 9443
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 150
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 9443
            timeoutSeconds: 30
          resources:
            limits:
              cpu: 3600m
              memory: 6500Mi
            requests:
              cpu: "2"
              memory: 5500Mi

          volumeMounts:
            - name: apim-store-publisher-bin
              mountPath: "/home/wso2carbon/kubernetes-volumes/am/bin/"
            - name: apim-store-publisher-conf
              mountPath: "/home/wso2carbon/kubernetes-volumes/am/conf/"
            - name: apim-store-publisher-identity
              mountPath: "/home/wso2carbon/kubernetes-volumes/am/conf-identity/"
            - name: apim-store-publisher-axis2
              mountPath: "/home/wso2carbon/kubernetes-volumes/am/conf-axis2/"
            - name: apim-store-publisher-datasources
              mountPath: "/home/wso2carbon/kubernetes-volumes/am/conf-datasources/"
            - name: apim-store-publisher-tomcat
              mountPath: "/home/wso2carbon/kubernetes-volumes/am/conf-tomcat/"
            - name: db-connector-jar
              mountPath: "/home/wso2carbon/kubernetes-volumes/am/mounting-jar"
            - name: apim-conf-entrypoint
              mountPath: "/home/wso2carbon/docker-entrypoint.sh"
              subPath: docker-entrypoint.sh
      serviceAccountName: "wso2svcacct"
      volumes:
        - name: apim-store-publisher-bin
          configMap:
            name: apim-store-publisher-bin
        - name: apim-store-publisher-conf
          configMap:
            name: apim-store-publisher-conf
        - name: apim-store-publisher-identity
          configMap:
            name: apim-store-publisher-identity
        - name: apim-store-publisher-axis2
          configMap:
            name: apim-store-publisher-axis2
        - name: apim-store-publisher-datasources
          configMap:
            name: apim-store-publisher-datasources
        - name: apim-store-publisher-tomcat
          configMap:
            name: apim-store-publisher-tomcat
        - name: db-connector-jar
          configMap:
            name: db-connector-jar
        - name: apim-conf-entrypoint
          configMap:
            name: apim-conf-entrypoint
            defaultMode: 0407