# This pod will be used to manage the artifacts in the mounted location.
apiVersion: v1
kind: Pod
metadata:
  name: backend-mi-pod
  namespace: wso2
spec:
  containers:
    - name: wso2mi
      image: virajhasith/wso2mi-4.1.0:latest
      imagePullPolicy: IfNotPresent
      ports:
        -
          containerPort: 8290
          protocol: "TCP"
        -
          containerPort: 8253
          protocol: "TCP"
      livenessProbe:
        failureThreshold: 3
        initialDelaySeconds: 60
        periodSeconds: 10
        successThreshold: 1
        tcpSocket:
          port: 8290
        timeoutSeconds: 10
      readinessProbe:
        failureThreshold: 3
        initialDelaySeconds: 60
        periodSeconds: 10
        successThreshold: 1
        tcpSocket:
          port: 8290
        timeoutSeconds: 30
      resources:
        limits:
          cpu: "2"
          memory: 4Gi
        requests:
          cpu: "2"
          memory: 2Gi